from __future__ import annotations

from pipeline.triton.flaggems_semantic_rules import resolve_semantic_mapping


def test_semantic_rule_templates_for_high_yield_ops() -> None:
    assert resolve_semantic_mapping("sub").intent_ops == ("sub",)
    assert resolve_semantic_mapping("mul").intent_ops == ("mul",)
    assert resolve_semantic_mapping("max").intent_ops == ("reduce_max",)
    assert resolve_semantic_mapping("max_dim").intent_ops == ("reduce_max",)
    assert resolve_semantic_mapping("sum_dim").intent_ops == ("reduce_sum",)
    assert resolve_semantic_mapping("mean").intent_ops == ("reduce_sum", "div")
    assert resolve_semantic_mapping("all").intent_ops == ("not", "reduce_any", "not")
    assert resolve_semantic_mapping("where_scalar_self").intent_ops == ("const", "where")
    assert resolve_semantic_mapping("where_scalar_other").intent_ops == ("const", "where")
    assert resolve_semantic_mapping("gather").intent_ops == ("gather",)
    assert resolve_semantic_mapping("flip").intent_ops == ("gather",)
    assert resolve_semantic_mapping("embedding").intent_ops == ("gather",)
    assert resolve_semantic_mapping("isin").intent_ops == ("broadcast_in_dim", "broadcast_in_dim", "ne", "not", "reduce_any")
    assert resolve_semantic_mapping("kron").intent_ops == ("kron",)
    assert resolve_semantic_mapping("linspace").intent_ops == ("iota", "cast", "sub", "div", "mul", "add")
    assert resolve_semantic_mapping("logspace").intent_ops == ("iota", "cast", "sub", "div", "mul", "add", "mul", "exp")
    assert resolve_semantic_mapping("masked_select").intent_ops == ("where", "nonzero", "gather")
    assert resolve_semantic_mapping("masked_scatter").intent_ops == ("where", "scatter")
    assert resolve_semantic_mapping("max_pool2d_with_indices").intent_ops == ("max_pool2d_with_indices", "max_pool2d_with_indices")
    assert resolve_semantic_mapping("conv1d").intent_ops == ("conv1d",)
    assert resolve_semantic_mapping("conv3d").intent_ops == ("conv3d",)
    assert resolve_semantic_mapping("conv_depthwise2d").intent_ops == ("conv_depthwise2d",)
    assert resolve_semantic_mapping("scatter").intent_ops == ("scatter",)
    assert resolve_semantic_mapping("select_scatter").intent_ops == ("where", "scatter")
    assert resolve_semantic_mapping("slice_scatter").intent_ops == ("where", "scatter")
    assert resolve_semantic_mapping("quantile").intent_ops == ("quantile",)
    assert resolve_semantic_mapping("polar").intent_ops == ("polar",)
    assert resolve_semantic_mapping("unique2").intent_ops == ("unique",)
    assert resolve_semantic_mapping("weight_norm_interface").intent_ops == ("mul", "reduce_sum", "sqrt", "div", "broadcast_in_dim", "mul")
    assert resolve_semantic_mapping("scaled_dot_product_attention").intent_ops == ("matmul", "softmax", "matmul")
    assert resolve_semantic_mapping("per_token_group_quant_fp8").intent_ops == ("per_token_group_quant_fp8",)
    assert resolve_semantic_mapping("trace").intent_ops == ("trace",)
    assert resolve_semantic_mapping("triu").intent_ops == ("triu",)
    assert resolve_semantic_mapping("upsample_nearest1d").intent_ops == ("upsample_nearest1d",)
    assert resolve_semantic_mapping("upsample_nearest2d").intent_ops == ("upsample_nearest2d",)
    assert resolve_semantic_mapping("mse_loss").intent_ops == ("mse_loss",)
    assert resolve_semantic_mapping("nan_to_num").intent_ops == ("nan_to_num",)
    assert resolve_semantic_mapping("nll_loss_forward").intent_ops == ("nll_loss_forward",)
    assert resolve_semantic_mapping("nll_loss2d_forward").intent_ops == ("nll_loss2d_forward",)
    assert resolve_semantic_mapping("one_hot").intent_ops == ("iota", "broadcast_in_dim", "ne", "not", "cast")
    assert resolve_semantic_mapping("glu").intent_ops == ("glu",)
    assert resolve_semantic_mapping("cummax").intent_ops == ("cummax",)
    assert resolve_semantic_mapping("cummin").intent_ops == ("cummin",)
    assert resolve_semantic_mapping("index_add").intent_ops == ("index_add",)
    assert resolve_semantic_mapping("index_put").intent_ops == ("where", "scatter")
    assert resolve_semantic_mapping("mm").intent_ops == ("cast", "cast", "matmul")
    assert resolve_semantic_mapping("bmm").intent_ops == ("cast", "cast", "matmul")
    assert resolve_semantic_mapping("dot").intent_ops == ("cast", "cast", "mul", "reduce_sum")
    assert resolve_semantic_mapping("addmm").intent_ops == ("matmul", "add")
    assert resolve_semantic_mapping("addcmul").intent_ops == ("const", "mul", "mul", "add")
    assert resolve_semantic_mapping("addcdiv").intent_ops == ("const", "mul", "div", "add")
    assert resolve_semantic_mapping("addr").intent_ops == ("const", "mul", "matmul", "const", "mul", "add")
    assert resolve_semantic_mapping("index_select").intent_ops == ("gather",)
    assert resolve_semantic_mapping("group_norm").intent_ops == ("reduce_sum", "sub", "mul", "add", "rsqrt", "broadcast_in_dim", "div")
    assert resolve_semantic_mapping("batch_norm").intent_ops == ("reduce_sum", "sub", "mul", "add", "rsqrt", "broadcast_in_dim", "div")
    assert resolve_semantic_mapping("rms_norm").intent_ops == ("mul", "reduce_sum", "add", "rsqrt", "mul")
    assert resolve_semantic_mapping("std").intent_ops == ("var", "sqrt")
    assert resolve_semantic_mapping("sort").intent_ops == ("sort",)
    assert resolve_semantic_mapping("stack").intent_ops == ("stack",)
    assert resolve_semantic_mapping("tan").intent_ops == ("tan",)
    assert resolve_semantic_mapping("tile").intent_ops == ("tile",)
    assert resolve_semantic_mapping("topk").intent_ops == ("topk",)
    assert resolve_semantic_mapping("isnan").intent_ops == ("ne",)
    assert resolve_semantic_mapping("isinf").intent_ops == ("abs", "const", "gt")
    assert resolve_semantic_mapping("isfinite").intent_ops == ("abs", "const", "le")
    assert resolve_semantic_mapping("acos").intent_ops == ("acos",)
    assert resolve_semantic_mapping("atan").intent_ops == ("atan",)
    assert resolve_semantic_mapping("angle").intent_ops == ("angle",)
    assert resolve_semantic_mapping("bitwise_and").intent_ops == ("bitwise_and",)
    assert resolve_semantic_mapping("bitwise_or").intent_ops == ("bitwise_or",)
    assert resolve_semantic_mapping("bitwise_not").intent_ops == ("bitwise_not",)
    assert resolve_semantic_mapping("bitwise_left_shift").intent_ops == ("bitwise_left_shift",)
    assert resolve_semantic_mapping("bitwise_right_shift").intent_ops == ("bitwise_right_shift",)
    assert resolve_semantic_mapping("count_nonzero").intent_ops == ("count_nonzero",)
    assert resolve_semantic_mapping("diag").intent_ops == ("diag",)
    assert resolve_semantic_mapping("diag_embed").intent_ops == ("diag_embed",)
    assert resolve_semantic_mapping("avg_pool2d").intent_ops == ("avg_pool2d",)
    assert resolve_semantic_mapping("eye").intent_ops == ("iota", "iota", "ne", "not", "cast")
    assert resolve_semantic_mapping("eye_m").intent_ops == ("iota", "iota", "ne", "not", "cast")
    assert resolve_semantic_mapping("celu").intent_ops == ("const", "gt", "exp", "const", "sub", "where")
    assert resolve_semantic_mapping("elu").intent_ops == ("const", "gt", "exp", "const", "sub", "where")


def test_semantic_rule_composite_aliases() -> None:
    assert resolve_semantic_mapping("all").intent_pattern_id == "reduce.all_via_not_any"
    assert resolve_semantic_mapping("eq").intent_ops == ("ne", "not")
    assert resolve_semantic_mapping("equal").intent_ops == ("ne", "not")
    assert resolve_semantic_mapping("maximum").intent_ops == ("max",)
    assert resolve_semantic_mapping("minimum").intent_ops == ("min",)
    assert resolve_semantic_mapping("ge_scalar").intent_ops == ("ge",)
    assert resolve_semantic_mapping("logical_and").intent_ops == ("and",)
    assert resolve_semantic_mapping("logical_not").intent_ops == ("not",)
    assert resolve_semantic_mapping("logical_or").intent_ops == ("or",)
    assert resolve_semantic_mapping("clamp_min").intent_ops == ("max",)
    assert resolve_semantic_mapping("zeros_like").intent_ops == ("const", "broadcast_in_dim")
    assert resolve_semantic_mapping("full_like").intent_ops == ("const", "broadcast_in_dim")
    assert resolve_semantic_mapping("pow_scalar").intent_ops == ("pow",)
    assert resolve_semantic_mapping("pow_tensor_scalar").intent_ops == ("pow",)
    assert resolve_semantic_mapping("pow_tensor_tensor").intent_ops == ("pow",)
    assert resolve_semantic_mapping("prod").intent_ops == ("reduce_prod",)
    assert resolve_semantic_mapping("prod_dim").intent_ops == ("reduce_prod",)
    assert resolve_semantic_mapping("remainder").intent_ops == ("remainder",)
    assert resolve_semantic_mapping("repeat").intent_ops == ("repeat",)
    assert resolve_semantic_mapping("lerp_scalar").intent_ops == ("sub", "mul", "add")
    assert resolve_semantic_mapping("rms_norm_forward").intent_ops == ("mul", "reduce_sum", "add", "rsqrt", "mul")
    assert resolve_semantic_mapping("cat").intent_ops == ("concat",)
    assert resolve_semantic_mapping("hstack").intent_ops == ("concat",)
    assert resolve_semantic_mapping("vstack").intent_ops == ("concat",)
    assert resolve_semantic_mapping("constant_pad_nd").intent_ops == ("pad",)
    assert resolve_semantic_mapping("repeat_interleave_self_int").intent_ops == ("repeat_interleave",)
    assert resolve_semantic_mapping("repeat_interleave_self_tensor").intent_ops == ("repeat_interleave",)
    assert resolve_semantic_mapping("repeat_interleave_tensor").intent_ops == ("repeat_interleave",)
    assert resolve_semantic_mapping("sort_stable").intent_ops == ("sort",)
    assert resolve_semantic_mapping("arange").intent_ops == ("iota",)
    assert resolve_semantic_mapping("bitwise_and_scalar").intent_ops == ("bitwise_and",)
    assert resolve_semantic_mapping("bitwise_and_tensor").intent_ops == ("bitwise_and",)
    assert resolve_semantic_mapping("bitwise_or_scalar").intent_ops == ("bitwise_or",)
    assert resolve_semantic_mapping("bitwise_or_tensor").intent_ops == ("bitwise_or",)
    assert resolve_semantic_mapping("logical_xor").intent_ops == ("or", "and", "not", "and")
    assert resolve_semantic_mapping("log_softmax").intent_ops == ("softmax", "log")
    assert resolve_semantic_mapping("exp2").intent_ops == ("const", "mul", "exp")
    assert resolve_semantic_mapping("sin").intent_ops == ("sin",)
    assert resolve_semantic_mapping("scaled_softmax_forward").intent_ops == ("reduce_max", "sub", "exp", "reduce_sum", "div")
    assert resolve_semantic_mapping("scaled_dot_product_attention_forward").intent_ops == ("matmul", "softmax", "matmul")
    assert resolve_semantic_mapping("flash_attention_forward").intent_ops == ("matmul", "softmax", "matmul")
    assert resolve_semantic_mapping("ScaleDotProductAttention").intent_ops == ("matmul", "softmax", "matmul")
    assert resolve_semantic_mapping("sigmoid").intent_ops == ("const", "mul", "exp", "add", "div")
    assert resolve_semantic_mapping("softplus").intent_ops == ("exp", "add", "log")
    assert resolve_semantic_mapping("var_mean").intent_ops == ("std", "mul")
    assert resolve_semantic_mapping("vector_norm").intent_ops == ("mul", "reduce_sum", "sqrt")
    assert resolve_semantic_mapping("isclose").intent_ops == ("sub", "abs", "abs", "mul", "add", "le")
    assert resolve_semantic_mapping("allclose").intent_ops == ("sub", "abs", "abs", "mul", "add", "le", "not", "reduce_any", "not")
    assert resolve_semantic_mapping("masked_fill").intent_ops == ("where",)
    assert resolve_semantic_mapping("threshold").intent_ops == ("const", "gt", "where")
