from __future__ import annotations

from pipeline.triton.flaggems_specs import coverage_flaggems_kernel_specs, default_flaggems_kernel_specs


def test_flaggems_specs_include_registry_metadata() -> None:
    specs = default_flaggems_kernel_specs(flaggems_opset="deterministic_forward", backend_target="rvv")
    assert specs
    for spec in specs:
        assert getattr(spec, "provider", None) == "flaggems"
        assert isinstance(getattr(spec, "source_op", None), str)
        assert isinstance(getattr(spec, "capability_state", None), str)


def test_flaggems_coverage_specs_include_expanded_semantics() -> None:
    specs = coverage_flaggems_kernel_specs(flaggems_opset="deterministic_forward", backend_target="rvv")
    names = {str(s.name) for s in specs}
    assert "relu2d" in names
    assert "celu2d" in names
    assert "elu2d" in names
    assert "exp2d" in names
    assert "exp22d" in names
    assert "acos2d" in names
    assert "atan2d" in names
    assert "angle2d" in names
    assert "cat2d" in names
    assert "arange1d" in names
    assert "addcmul2d" in names
    assert "addcdiv2d" in names
    assert "addr2d" in names
    assert "bitwise_and2d" in names
    assert "bitwise_or2d" in names
    assert "bitwise_not2d" in names
    assert "bitwise_left_shift2d" in names
    assert "bitwise_right_shift2d" in names
    assert "avg_pool2d_nchw" in names
    assert "argmax2d" in names
    assert "argmin2d" in names
    assert "conv1d_ncl" in names
    assert "conv2d_nchw" in names
    assert "conv3d_ncdhw" in names
    assert "conv_depthwise2d_nchw" in names
    assert "scatter2d" in names
    assert "select_scatter2d" in names
    assert "slice_scatter2d" in names
    assert "quantile2d" in names
    assert "polar2d" in names
    assert "unique2d" in names
    assert "weight_norm2d" in names
    assert "scaled_dot_product_attention_bhsd" in names
    assert "flash_attn_varlen_func_bhsd" in names
    assert "trace2d" in names
    assert "triu2d" in names
    assert "upsample_nearest1d_ncl" in names
    assert "upsample_nearest2d_nchw" in names
    assert "count_nonzero2d" in names
    assert "diag2d" in names
    assert "diag_embed2d" in names
    assert "div2d" in names
    assert "eq2d" in names
    assert "ne2d" in names
    assert "gt2d" in names
    assert "ge2d" in names
    assert "lt2d" in names
    assert "le2d" in names
    assert "neg2d" in names
    assert "ceil2d" in names
    assert "reciprocal2d" in names
    assert "sqrt2d" in names
    assert "silu2d" in names
    assert "tanh2d" in names
    assert "logical_and2d" in names
    assert "logical_or2d" in names
    assert "logical_not2d" in names
    assert "logical_xor2d" in names
    assert "mm2d" in names
    assert "bmm3d" in names
    assert "addmm2d" in names
    assert "baddbmm3d" in names
    assert "dot1d" in names
    assert "vdot1d" in names
    assert "mv2d" in names
    assert "addmv2d" in names
    assert "sub2d" in names
    assert "mul2d" in names
    assert "sigmoid2d" in names
    assert "cos2d" in names
    assert "erf2d" in names
    assert "gelu2d" in names
    assert "log2d" in names
    assert "log_sigmoid2d" in names
    assert "log_softmax2d" in names
    assert "sin2d" in names
    assert "softplus2d" in names
    assert "sort2d" in names
    assert "sort_stable2d" in names
    assert "stack2d" in names
    assert "std2d" in names
    assert "tan2d" in names
    assert "tile2d" in names
    assert "topk2d" in names
    assert "var_mean2d" in names
    assert "vector_norm2d" in names
    assert "remainder2d" in names
    assert "abs2d" in names
    assert "rsqrt2d" in names
    assert "where2d" in names
    assert "row_sum" in names
    assert "prod2d" in names
    assert "prod_dim2d" in names
    assert "row_mean" in names
    assert "row_all" in names
    assert "row_max" in names
    assert "min2d" in names
    assert "min_dim2d" in names
    assert "nonzero2d" in names
    assert "normed_cumsum2d" in names
    assert "allclose2d" in names
    assert "isclose2d" in names
    assert "isfinite2d" in names
    assert "isinf2d" in names
    assert "isnan2d" in names
    assert "masked_fill2d" in names
    assert "threshold2d" in names
    assert "pad2d" in names
    assert "constant_pad_nd2d" in names
    assert "hstack2d" in names
    assert "vstack2d" in names
    assert "full2d" in names
    assert "eye2d" in names
    assert "eye_m2d" in names
    assert "maximum2d" in names
    assert "minimum2d" in names
    assert "identity2d" in names
    assert "cast2d" in names
    assert "flip2d" in names
    assert "repeat2d" in names
    assert "repeat_interleave_self_int1d" in names
    assert "repeat_interleave_self_tensor1d" in names
    assert "repeat_interleave_tensor1d" in names
    assert "embedding2d" in names
    assert "isin1d" in names
    assert "kron2d" in names
    assert "linspace1d" in names
    assert "logspace1d" in names
    assert "masked_select2d" in names
    assert "masked_scatter2d" in names
    assert "max_pool2d_with_indices_nchw" in names
    assert "mse_loss2d" in names
    assert "nan_to_num2d" in names
    assert "nll_loss_forward" in names
    assert "nll_loss2d_forward" in names
    assert "one_hot2d" in names
    assert "glu2d" in names
    assert "cumsum2d" in names
    assert "cummax1d" in names
    assert "cummin1d" in names
    assert "index_add2d" in names
    assert "index_put2d" in names
    assert "gather2d" in names
    assert "index_select2d" in names
    assert "clamp2d" in names
    assert "pow_scalar2d" in names
    assert "pow_tensor_scalar2d" in names
    assert "pow_tensor_tensor2d" in names
    assert "per_token_group_quant_fp8_2d" in names
    assert "lerp2d" in names
    assert "batch_norm2d" in names
    assert "rms_norm2d" in names
