from __future__ import annotations

from pipeline.triton.flaggems_semantic_rules import resolve_semantic_mapping


def test_semantic_rule_templates_for_high_yield_ops() -> None:
    assert resolve_semantic_mapping("sub").intent_ops == ("sub",)
    assert resolve_semantic_mapping("mul").intent_ops == ("mul",)
    assert resolve_semantic_mapping("max").intent_ops == ("reduce_max",)
    assert resolve_semantic_mapping("max_dim").intent_ops == ("reduce_max",)
    assert resolve_semantic_mapping("sum_dim").intent_ops == ("reduce_sum",)
    assert resolve_semantic_mapping("mean").intent_ops == ("reduce_sum", "div")
    assert resolve_semantic_mapping("all").intent_ops == ("not", "reduce_any", "not")
    assert resolve_semantic_mapping("where_scalar_self").intent_ops == ("where",)
    assert resolve_semantic_mapping("where_scalar_other").intent_ops == ("where",)
    assert resolve_semantic_mapping("gather").intent_ops == ("gather",)
    assert resolve_semantic_mapping("mm").intent_ops == ("matmul",)
    assert resolve_semantic_mapping("addmm").intent_ops == ("matmul", "add")
    assert resolve_semantic_mapping("addcmul").intent_ops == ("const", "mul", "mul", "add")
    assert resolve_semantic_mapping("addcdiv").intent_ops == ("const", "mul", "div", "add")
    assert resolve_semantic_mapping("addr").intent_ops == ("const", "mul", "matmul", "const", "mul", "add")
    assert resolve_semantic_mapping("index_select").intent_ops == ("gather",)
    assert resolve_semantic_mapping("group_norm").intent_ops == ("reduce_sum", "sub", "mul", "add", "rsqrt", "broadcast_in_dim", "div")
    assert resolve_semantic_mapping("batch_norm").intent_ops == ("reduce_sum", "sub", "mul", "add", "rsqrt", "broadcast_in_dim", "div")
    assert resolve_semantic_mapping("rms_norm").intent_ops == ("mul", "reduce_sum", "add", "rsqrt", "mul")
    assert resolve_semantic_mapping("isnan").intent_ops == ("ne",)
    assert resolve_semantic_mapping("isinf").intent_ops == ("abs", "const", "gt")
    assert resolve_semantic_mapping("isfinite").intent_ops == ("abs", "const", "le")
    assert resolve_semantic_mapping("acos").intent_ops == ("acos",)
    assert resolve_semantic_mapping("atan").intent_ops == ("atan",)


def test_semantic_rule_composite_aliases() -> None:
    assert resolve_semantic_mapping("all").intent_pattern_id == "reduce.all_via_not_any"
    assert resolve_semantic_mapping("eq").intent_ops == ("ne", "not")
    assert resolve_semantic_mapping("equal").intent_ops == ("ne", "not")
    assert resolve_semantic_mapping("maximum").intent_ops == ("max",)
    assert resolve_semantic_mapping("minimum").intent_ops == ("min",)
    assert resolve_semantic_mapping("ge_scalar").intent_ops == ("ge",)
    assert resolve_semantic_mapping("logical_and").intent_ops == ("and",)
    assert resolve_semantic_mapping("logical_not").intent_ops == ("not",)
    assert resolve_semantic_mapping("logical_or").intent_ops == ("or",)
    assert resolve_semantic_mapping("clamp_min").intent_ops == ("max",)
    assert resolve_semantic_mapping("zeros_like").intent_ops == ("const", "broadcast_in_dim")
    assert resolve_semantic_mapping("full_like").intent_ops == ("const", "broadcast_in_dim")
    assert resolve_semantic_mapping("pow_scalar").intent_ops == ("pow",)
    assert resolve_semantic_mapping("lerp_scalar").intent_ops == ("sub", "mul", "add")
    assert resolve_semantic_mapping("rms_norm_forward").intent_ops == ("mul", "reduce_sum", "add", "rsqrt", "mul")
    assert resolve_semantic_mapping("cat").intent_ops == ("concat",)
    assert resolve_semantic_mapping("hstack").intent_ops == ("concat",)
    assert resolve_semantic_mapping("vstack").intent_ops == ("concat",)
    assert resolve_semantic_mapping("constant_pad_nd").intent_ops == ("pad",)
    assert resolve_semantic_mapping("repeat_interleave_self_int").intent_ops == ("repeat_interleave",)
    assert resolve_semantic_mapping("sort_stable").intent_ops == ("sort",)
    assert resolve_semantic_mapping("arange").intent_ops == ("iota",)
    assert resolve_semantic_mapping("logical_xor").intent_ops == ("or", "and", "not", "and")
    assert resolve_semantic_mapping("log_softmax").intent_ops == ("softmax", "log")
    assert resolve_semantic_mapping("exp2").intent_ops == ("const", "mul", "exp")
    assert resolve_semantic_mapping("scaled_softmax_forward").intent_ops == ("softmax",)
    assert resolve_semantic_mapping("sigmoid").intent_ops == ("const", "mul", "exp", "add", "div")
    assert resolve_semantic_mapping("softplus").intent_ops == ("exp", "add", "log")
    assert resolve_semantic_mapping("isclose").intent_ops == ("sub", "abs", "abs", "mul", "add", "le")
    assert resolve_semantic_mapping("allclose").intent_ops == ("sub", "abs", "abs", "mul", "add", "le", "not", "reduce_any", "not")
    assert resolve_semantic_mapping("masked_fill").intent_ops == ("where",)
    assert resolve_semantic_mapping("threshold").intent_ops == ("const", "gt", "where")
