#!/usr/bin/env python3
"""
Provision a repository-local MLIR toolchain without sudo.

Default strategy:
1) `apt download mlir-<version>-tools`
2) `dpkg-deb -x` into `artifacts/toolchains/mlir-<version>`
3) create stable symlink `artifacts/toolchains/mlir-current`
4) write env helper script + json summary
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TOOLCHAIN_ROOT = ROOT / "artifacts" / "toolchains"


def _run(cmd: list[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=(str(cwd) if cwd is not None else None), capture_output=True, text=True)


def _require_ok(p: subprocess.CompletedProcess[str], *, step: str) -> None:
    if p.returncode == 0:
        return
    out = str(p.stdout or "").strip()
    err = str(p.stderr or "").strip()
    detail = "\n".join([x for x in [out, err] if x])
    raise RuntimeError(f"{step} failed (rc={p.returncode}){(': ' + detail) if detail else ''}")


def _find_tool(root: Path, *, tool: str, version: int) -> Path:
    candidates = [
        root / "bin" / tool,
        root / "usr" / "bin" / tool,
        root / "usr" / "bin" / f"{tool}-{version}",
        root / "usr" / "lib" / f"llvm-{version}" / "bin" / tool,
        root / "lib" / f"llvm-{version}" / "bin" / tool,
    ]
    for p in candidates:
        if p.is_file() and os.access(str(p), os.X_OK):
            return p
    raise FileNotFoundError(
        f"cannot find executable `{tool}` under {root}. checked: {', '.join(str(x) for x in candidates)}"
    )


def _symlink_force(dst: Path, src: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    rel = os.path.relpath(str(src), str(dst.parent))
    dst.symlink_to(rel)


def _write_env_file(
    *,
    env_file: Path,
    toolchain_root: Path,
    mlir_opt: Path,
    mlir_translate: Path,
    llvm_as: str,
    llvm_opt: str,
) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by scripts/intentir/provision_mlir_toolchain.py",
        f"export INTENTIR_MLIR_TOOLCHAIN_ROOT='{toolchain_root}'",
        f"export INTENTIR_MLIR_OPT='{mlir_opt}'",
        f"export INTENTIR_MLIR_TRANSLATE='{mlir_translate}'",
    ]
    if llvm_as:
        lines.append(f"export INTENTIR_LLVM_AS='{llvm_as}'")
    if llvm_opt:
        lines.append(f"export INTENTIR_LLVM_OPT='{llvm_opt}'")
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    env_file.chmod(0o755)


def _tool_version(path: Path) -> str:
    p = _run([str(path), "--version"])
    if p.returncode != 0:
        return ""
    line = str((p.stdout or p.stderr or "").splitlines()[0]).strip()
    return line


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", type=int, default=14, help="Ubuntu MLIR package major version (default: 14).")
    ap.add_argument(
        "--prefix",
        type=Path,
        default=None,
        help="Install prefix (default: artifacts/toolchains/mlir-<version>).",
    )
    ap.add_argument(
        "--toolchain-root",
        type=Path,
        default=DEFAULT_TOOLCHAIN_ROOT,
        help="Toolchain root dir (default: artifacts/toolchains).",
    )
    ap.add_argument(
        "--current-link",
        type=Path,
        default=None,
        help="Symlink path to active toolchain (default: <toolchain-root>/mlir-current).",
    )
    ap.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Output env helper (default: <toolchain-root>/mlir-current/env.sh).",
    )
    ap.add_argument("--force", action=argparse.BooleanOptionalAction, default=False)
    ap.add_argument(
        "--use-current-link",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Maintain <toolchain-root>/mlir-current symlink (default: true).",
    )
    ap.add_argument("--out", type=Path, default=None, help="Optional json summary path.")
    args = ap.parse_args()

    version = int(args.version)
    toolchain_root = Path(args.toolchain_root)
    prefix = Path(args.prefix) if args.prefix is not None else (toolchain_root / f"mlir-{version}")
    current_link = Path(args.current_link) if args.current_link is not None else (toolchain_root / "mlir-current")

    if prefix.exists():
        if not bool(args.force):
            raise SystemExit(f"target prefix already exists: {prefix} (use --force to replace)")
        if prefix.is_symlink() or prefix.is_file():
            prefix.unlink()
        else:
            shutil.rmtree(prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)

    pkg = f"mlir-{version}-tools"
    with tempfile.TemporaryDirectory(prefix="intentir_mlir_pkg_") as td:
        tmp = Path(td)
        p_dl = _run(["apt", "download", pkg], cwd=tmp)
        _require_ok(p_dl, step=f"apt download {pkg}")
        debs = sorted(tmp.glob(f"{pkg}_*_amd64.deb"))
        if not debs:
            raise RuntimeError(f"download succeeded but no .deb matched {pkg}_*_amd64.deb")
        deb = debs[-1]
        p_x = _run(["dpkg-deb", "-x", str(deb), str(prefix)])
        _require_ok(p_x, step="dpkg-deb -x")

    mlir_opt = _find_tool(prefix, tool="mlir-opt", version=version)
    mlir_translate = _find_tool(prefix, tool="mlir-translate", version=version)

    # Provide stable non-versioned entrypoints under <prefix>/bin for discovery.
    bin_dir = prefix / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    _symlink_force(bin_dir / "mlir-opt", mlir_opt)
    _symlink_force(bin_dir / "mlir-translate", mlir_translate)

    if bool(args.use_current_link):
        if current_link.exists() or current_link.is_symlink():
            current_link.unlink()
        current_link.parent.mkdir(parents=True, exist_ok=True)
        rel = os.path.relpath(str(prefix), str(current_link.parent))
        current_link.symlink_to(rel)

    llvm_as = shutil.which("llvm-as") or ""
    llvm_opt = shutil.which("opt") or ""

    env_file = Path(args.env_file) if args.env_file is not None else (current_link / "env.sh")
    _write_env_file(
        env_file=env_file,
        toolchain_root=(current_link if bool(args.use_current_link) else prefix),
        mlir_opt=(bin_dir / "mlir-opt"),
        mlir_translate=(bin_dir / "mlir-translate"),
        llvm_as=str(llvm_as),
        llvm_opt=str(llvm_opt),
    )

    summary: dict[str, Any] = {
        "schema_version": "intentir_mlir_toolchain_provision_v1",
        "ok": True,
        "version": int(version),
        "package": str(pkg),
        "prefix": str(prefix),
        "current_link": (str(current_link) if bool(args.use_current_link) else ""),
        "env_file": str(env_file),
        "tools": {
            "mlir-opt": {"path": str(bin_dir / "mlir-opt"), "version": _tool_version(bin_dir / "mlir-opt")},
            "mlir-translate": {
                "path": str(bin_dir / "mlir-translate"),
                "version": _tool_version(bin_dir / "mlir-translate"),
            },
            "llvm-as": {"path": str(llvm_as), "version": ""},
            "opt": {"path": str(llvm_opt), "version": ""},
        },
        "next_steps": [
            f"source {env_file}",
            "python scripts/intentir.py mlir check",
        ],
    }

    if args.out is not None:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"[intentir] wrote {out}")

    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
