"""
Shared source loader for IntentIR quality scripts.

This provides a registry-like entry stream from either:
- a FlagGems registry JSON (`entries[].intent_ops`)
- an MLIR manifest (`entries[].module_path/module_text`) where each module
  contains recoverable intent payload generated by IntentIR MLIR bridge.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from intent_ir.mlir import to_intent


def load_entries(
    *,
    registry_path: Path | None = None,
    mlir_manifest_path: Path | None = None,
) -> tuple[list[dict[str, Any]], str]:
    if mlir_manifest_path is not None:
        return _load_from_mlir_manifest(mlir_manifest_path), f"mlir_manifest:{mlir_manifest_path}"
    if registry_path is None:
        raise ValueError("either registry_path or mlir_manifest_path must be provided")
    if not registry_path.is_file():
        raise FileNotFoundError(f"registry not found: {registry_path}")
    payload = json.loads(registry_path.read_text(encoding="utf-8"))
    entries = [e for e in list(payload.get("entries") or []) if isinstance(e, dict)]
    return entries, f"registry:{registry_path}"


def _load_from_mlir_manifest(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(f"mlir manifest not found: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows_raw = payload if isinstance(payload, list) else payload.get("entries")
    if not isinstance(rows_raw, list):
        raise ValueError(f"mlir manifest invalid (expected list or entries list): {path}")

    out: list[dict[str, Any]] = []
    for idx, row in enumerate(rows_raw):
        if not isinstance(row, dict):
            continue
        module_text = _module_text_from_row(row, base_dir=path.parent, row_index=idx, manifest_path=path)
        intent = to_intent(module_text)
        ops = [str(op.op) for op in list(intent.ops or []) if str(getattr(op, "op", "")).strip()]
        out.append(
            {
                "semantic_op": str(row.get("semantic_op") or intent.name or f"row_{idx}"),
                "family": str(row.get("family") or "unknown"),
                "mapping_kind": str(row.get("mapping_kind") or ""),
                "intent_ops": ops,
                "status": str(row.get("status") or ""),
                "status_reason": str(row.get("status_reason") or ""),
                "e2e_spec": row.get("e2e_spec"),
            }
        )
    return out


def _module_text_from_row(
    row: dict[str, Any],
    *,
    base_dir: Path,
    row_index: int,
    manifest_path: Path,
) -> str:
    if isinstance(row.get("module_text"), str) and str(row.get("module_text")).strip():
        return str(row.get("module_text"))
    module_path_raw = str(row.get("module_path") or "").strip()
    if not module_path_raw:
        raise ValueError(
            f"mlir manifest row {row_index} missing module_text/module_path: {manifest_path}"
        )
    module_path = Path(module_path_raw)
    if not module_path.is_absolute():
        module_path = (base_dir / module_path).resolve()
    if not module_path.is_file():
        raise FileNotFoundError(f"mlir module_path not found: {module_path}")
    return module_path.read_text(encoding="utf-8")

