"""
CUDA backend supported op set (WIP).

This reflects currently implemented lowering paths in `intentir_to_cuda.py`
(direct kernels + fused patterns + generic fused elementwise).
"""

from __future__ import annotations


CUDA_SUPPORTED_OPS: set[str] = {
    # Single-op semantic kernels.
    "matmul",
    "conv1d",
    "conv2d",
    "conv3d",
    "conv_depthwise2d",
    "max_pool2d_with_indices",
    "mse_loss",
    "dropout",
    "softmax",
    "correlation",
    "resize",
    "warp",
    "rope",
    # Tensor transforms / indexing.
    "transpose",
    "gather",
    "scatter",
    "select_scatter",
    "slice_scatter",
    "nonzero",
    "index_add",
    "index_put",
    "masked_select",
    "masked_scatter",
    "kron",
    "concat",
    "pad",
    "glu",
    # Core primitives covered by pattern + fused elementwise lowerings.
    "const",
    "iota",
    "identity",
    "broadcast_in_dim",
    "cast",
    "reduce_sum",
    "reduce_prod",
    "reduce_max",
    "reduce_min",
    "reduce_any",
    "add",
    "sub",
    "mul",
    "div",
    "pow",
    "remainder",
    "max",
    "min",
    "relu",
    "abs",
    "exp",
    "log",
    "acos",
    "atan",
    "sin",
    "cos",
    "erf",
    "floor",
    "ceil",
    "rsqrt",
    "ne",
    "eq",
    "lt",
    "le",
    "gt",
    "ge",
    "bitwise_and",
    "bitwise_or",
    "bitwise_left_shift",
    "bitwise_right_shift",
    "bitwise_not",
    "and",
    "or",
    "not",
    "where",
    "argmax",
    "argmin",
    "quantile",
    "cumsum",
    "cummax",
    "cummin",
    "avg_pool2d",
    "scaled_dot_product_attention",
    "polar",
    "per_token_group_quant_fp8",
    "nll_loss_forward",
    "nll_loss2d_forward",
}

__all__ = ["CUDA_SUPPORTED_OPS"]
